events {}
http {
  server {
    listen 8091;
    server_name _;
    location / {
      proxy_pass http://haeon-attack-console:8094;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
  server {
    listen 8090;
    server_name haeon-attack.localhost;
    location / {
      proxy_pass http://haeon-attack-console:8094;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
  server {
    listen 8090 default_server;
    server_name haeon.localhost _;
    location = /merchant { return 302 /merchant/; }
    location /internal/ { return 404; }
    location /control/ { return 404; }
    location /merchant/ {
      proxy_pass http://haeon-merchant-support:8091;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location /lab-shell/ {
      proxy_pass http://haeon-merchant-support:8091;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location / {
      proxy_pass http://haeon-card:8085;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
